export const data = [
  {
    id: 1,
    nombre: "Tlayuda con Tasajo",
    img: "../../assets/IMG/comida.jpg",
    descripcion: "Tlayuda tradicional con tasajo, frijoles, queso y aguacate.",
    precio: 66,
    categoria: "Platillo principal",
    stock: 13,
  },
  {
    id: 2,
    nombre: "Mole Negro",
    img: "../../assets/IMG/comida.jpg",
    descripcion:
      "Mole negro oaxaqueño con pollo, acompañado de arroz y tortillas.",
    precio: 80,
    categoria: "Platillo principal",
    stock: 13,
  },
  {
    id: 3,
    nombre: "Tamales de Mole",
    img: "../../assets/IMG/comida.jpg",
    descripcion:
      "Tamales envueltos en hoja de plátano, rellenos de mole negro y pollo.",
    precio: 30,
    categoria: "Entrada",
    stock: 13,
  },
  {
    id: 4,
    nombre: "Enchiladas de Coloradito",
    img: "../../assets/IMG/comida.jpg",
    descripcion:
      "Enchiladas bañadas en salsa coloradito, rellenas de pollo y queso.",
    precio: 80,
    categoria: "Platillo principal",
    stock: 13,
  },
  {
    id: 5,
    nombre: "Chapulines",
    img: "../../assets/IMG/comida.jpg",
    descripcion: "Chapulines tostados con ajo y sal de gusano.",
    precio: 29,
    categoria: "Botana",
    stock: 13,
  },
  {
    id: 6,
    nombre: "Mezcal Joven",
    img: "../../assets/IMG/comida.jpg",
    descripcion:
      "Vaso de mezcal joven artesanal, servido con rodajas de naranja.",
    precio: 60,
    categoria: "Bebida",
    stock: 13,
  },
  {
    id: 7,
    nombre: "Empanadas de Amarillo",
    img: "../../assets/IMG/comida.jpg",
    descripcion: "Empanadas rellenas de mole amarillo y pollo, hechas a mano.",
    precio: 100,
    categoria: "Entrada",
    stock: 13,
  },
  {
    id: 8,
    nombre: "Agua de Horchata con Tuna",
    img: "../../assets/IMG/comida.jpg",
    descripcion: "Agua fresca de horchata con tuna, nuez y melón.",
    precio: 34,
    categoria: "Bebida",
    stock: 13,
  },
  {
    id: 9,
    nombre: "Memelas",
    img: "../../assets/IMG/comida.jpg",
    descripcion:
      "Tortillas gruesas de maíz, untadas con frijoles y queso fresco.",
    precio: 77,
    categoria: "Entrada",
    stock: 13,
  },
  {
    id: 10,
    nombre: "Caldo de Piedra",
    img: "../../assets/IMG/comida.jpg",
    descripcion:
      "Sopa tradicional hecha con pescado y camarones, cocida con piedras calientes.",
    precio: 220,
    categoria: "Platillo principal",
    stock: 13,
  },
  {
    id: 11,
    nombre: "Mezcal Joven",
    img: "../../assets/IMG/comida.jpg",
    descripcion:
      "Vaso de mezcal joven artesanal, servido con rodajas de naranja.",
    precio: 120,
    categoria: "Bebida",
    stock: 13,
  },
  {
    id: 12,
    nombre: "Empanadas de Amarillo",
    img: "../../assets/IMG/comida.jpg",
    descripcion: "Empanadas rellenas de mole amarillo y pollo, hechas a mano.",
    precio: 16,
    categoria: "Entrada",
    stock: 13,
  },
  {
    id: 13,
    nombre: "Agua de Horchata con Tuna",
    img: "../../assets/IMG/comida.jpg",
    descripcion: "Agua fresca de horchata con tuna, nuez y melón.",
    precio: 45,
    categoria: "Bebida",
    stock: 13,
  },
  {
    id: 14,
    nombre: "Memelas",
    img: "../../assets/IMG/comida.jpg",
    descripcion:
      "Tortillas gruesas de maíz, untadas con frijoles y queso fresco.",
    precio: 66,
    categoria: "Entrada",
    stock: 13,
  },
  {
    id: 15,
    nombre: "Caldo de Piedra",
    img: "../../assets/IMG/comida.jpg",
    descripcion:
      "Sopa tradicional hecha con pescado y camarones, cocida con piedras calientes.",
    precio: 66,
    categoria: "Platillo principal",
    stock: 13,
  },
];
